config/routes.rb
# == Route Map
#
#          Prefix Verb   URI Pattern                        Controller#Action
#            root GET    /                                  users#login_form
# login_form_post POST   /login_form_post(.:format)         users#login_form_post
#           users GET    /users(.:format)                   users#index
#                 POST   /users(.:format)                   users#create
#        new_user GET    /users/new(.:format)               users#new
#       edit_user GET    /users/:id/edit(.:format)          users#edit
#            user GET    /users/:id(.:format)               users#show
#                 PATCH  /users/:id(.:format)               users#update
#                 PUT    /users/:id(.:format)               users#update
#                 DELETE /users/:id(.:format)               users#destroy
#      rest_login POST   /rest/login(.:format)              rest/login#login {:format=>:json}
#            rest POST   /rest/verify_user/:email(.:format) rest/login#verify_user {:format=>:json}
#

Rails.application.routes.draw do
  root to: 'users#login_form'
  post '/login_form_post', to: 'users#login_form_post'
  resources :users
  namespace :rest, defaults: { format: :json } do
    post '/login', to: 'login#login'
    post '/verify_user/:email', to: 'login#verify_user', constraints: { site_name: /[a-zA-Z1-9\.]+/ }
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  email      :string
#  image      :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ApplicationRecord
  validates :email, presence: true, uniqueness: { case_sensitive: false }
  validates :image, presence: true

  def validate_image(image)
    if self.image.eql? image
      true
    else
      false
    end
  end


  # Levenshtein method take too long.
  # require 'levenshtein'

  # def validate_image(image)
  #   percent = User.distance_percent(self.image, image)
  #   if percent > 10 || percent == 0
  #     false
  #   else
  #     true
  #   end
  # end

  # def self.distance_percent(first, second)
  #   max_distance = [first, second].max_by(&:length).length
  #   distance = Levenshtein.distance(first, second)
  #   (100.0 / max_distance * distance).round
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery prepend: true, with: :exception
end

app/controllers/rest/login_controller.rb
module Rest
  class LoginController < ApplicationController
    # WebService 1. It calls WebService 2 and return the response to the user
    def login
      require 'net/http'
      require 'uri'
      params = {'image' => login_params[:image]}
      parsed_uri = URI.parse(request.base_url + '/rest/verify_user/' +
                             login_params[:email].gsub!(".","%2e"))

      resp = Net::HTTP.post_form(parsed_uri, params)
      if resp.code.eql? '200'
        render json: {message: 'OK'}, status: :ok
      elsif resp.code.eql? '401'
        render json: {message: 'No Autorizado'}, status: :unauthorized
      else
        render json: {message: 'Bad Request'}, status: :bad_request
      end
    end

    # WebService 2. It make the verification of the image and return the
    # response to the WebService 1. Also send the email to user.
    def verify_user
      user = User.where(email: login_params[:email]).first
      if user && user.validate_image(login_params[:image])
        UserNotifierMailer.send_login_email(user, request.user_agent, true).deliver
        render json: {message: 'OK'}, status: :ok
      else
        UserNotifierMailer.send_login_email(user, request.user_agent, false).deliver
        render json: {message: 'No Autorizado'}, status: :unauthorized
      end
    end

    private
    def login_params
      params.permit(:image, :email)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  require 'net/http'
  require 'uri'
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.image = Base64.encode64(open(user_params[:image].tempfile.path) { |io| io.read })

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # Set the user to the form.
  def login_form
    @user = User.new
  end

  # Make the magic. It calls to the WebService.
  def login_form_post
    begin
      params = {'image' => Base64.encode64(open(user_params[:image].tempfile.path) { |io| io.read }),
                'email' => user_params[:email]}
      parsed_uri = URI.parse(request.base_url + '/rest/login/')
      resp = Net::HTTP.post_form(parsed_uri, params)
    rescue => e
      Rails.logger.debug(e)
    ensure
      redirect_to root_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AcidChallenge</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_login_form.html.erb
<%= form_with(local: true, url: login_form_post_url, model: user) do |form| %>
  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit 'Log in' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= image_tag "data:image/jpeg;base64,#{user.image}", size: 100 %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/login_form.html.erb
<h1>Login Form</h1>
<%= render 'login_form', user: @user %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag "data:image/jpeg;base64,#{@user.image}" %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>